version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 08138731632ibe
      POSTGRES_DB: vetconnect
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  web:
    build: .
    environment:
      FLASK_ENV: production
      SECRET_KEY: "change-me"
      DATABASE_URL: "postgresql+psycopg2://vet:vetpass@db:5432/vetconnect"
      MAIL_SERVER: "smtp.gmail.com"
      MAIL_PORT: 587
      MAIL_USERNAME: "benedictaoibeawuchi@gmail.com"
      MAIL_PASSWORD: "08138731632!Be"
      MAIL_DEFAULT_SENDER: "noreply@vetconnect.com"
    ports: ["8080:8080"]
    depends_on: [db]

volumes:
  pgdata: